name: test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test_linux:
    name: "test on linux"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: |
          script/setup --dev
      - name: test
        run: |
          test $(script/run --version) = $(cat wyoming_faster_whisper/VERSION)
          script/lint
          script/test
